### ISSUE TITLE
error for a formosat product

### ISSUE THREAD

**Issue by jteulade** [sertit/eoreader#167]
For this product: `s3://sertit-projects-archives/projects/2017/EEOS_Malaria/Bamako/Bamako/formosat-2010-11-19 pan.zip`

I get this error:

````
Traceback (most recent call last):
  File "E:\JTeulade\repositories\stac\scripts\test.py", line 25, in <module>
    func()
  File "E:\JTeulade\repositories\stac\libs\sertit-utils\sertit\s3.py", line 118, in s3_env_wrapper
    return function(*_args, **_kwargs)
  File "E:\JTeulade\repositories\stac\scripts\test.py", line 17, in func
    prod: Product = Reader().open(tata, remove_tmp=True, method=CheckMethod.MTD)
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 528, in open
    prod = self._open_path(
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 690, in _open_path
    prod = create_product(
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 957, in create_product
    prod = class_(
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\vhr_product.py", line 91, in __init__
    super().__init__(product_path, archive_path, output_path, remove_tmp, **kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\optical_product.py", line 116, in __init__
    super().__init__(product_path, archive_path, output_path, remove_tmp, **kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\product.py", line 241, in __init__
    self._pre_init(**kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\spot45_product.py", line 211, in _pre_init
    raise InvalidProductError("Mission index should be 4 or 5.")
eoreader.exceptions.InvalidProductError: Mission index should be 4 or 5.
```
This is due to a very old product: formosat

**Comment by remi-braun** [comment]
Old Formosat-2 products are basically SPOT-4/5 products. It could be very easy to handle. To do if it's only really quick to realise.
