### ISSUE TITLE
Unable to read Sentinel-2 products from archive

### ISSUE THREAD

**Issue by zoepapirer** [sertit/eoreader#168]
When given an archive for S2 products, eoreader raises an exception when it is trying to access the band data.
This error was encountered when tested through extreactEO.

It works like intended when given a SAFE product, only the archive creates an issue.

This is the complete error :

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/extracteo/orchestrators/sequential.py", line 264, in run_sequential
    module.in_product_loop(eeo_data)
  File "/usr/local/lib/python3.9/site-packages/extracteo/modules/analysis/emsr_formatting.py", line 269, in in_product_loop
    stack_path = self.stack(
  File "/usr/local/lib/python3.9/site-packages/extracteo/modules/analysis/emsr_formatting.py", line 360, in stack
    prod.stack(
  File "/usr/local/lib/python3.9/site-packages/eoreader/products/product.py", line 1668, in stack
    band_xds = self.load(bands, pixel_size=pixel_size, size=size, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/eoreader/products/product.py", line 891, in load
    band_xds = self._load(unique_bands, pixel_size, size, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/eoreader/products/product.py", line 989, in _load
    loaded_bands = self._load_bands(
  File "/usr/local/lib/python3.9/site-packages/eoreader/products/optical/s2_product.py", line 1227, in _load_bands
    band_paths = self.get_band_paths(bands, pixel_size=pixel_size, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/eoreader/products/optical/s2_product.py", line 646, in get_band_paths
    raise InvalidProductError(
eoreader.exceptions.InvalidProductError: Non existing SpectralBandNames.RED (04) band for /home/data/DATA/test_EEO/S2B_MSIL1C_20240507T155819_N0510_R097_T17TQG_20240507T193837.zip
```

 - eoreader version: 0.21.1 (through extractEO stable)

**Comment by remi-braun** [comment]
Fixed 😉 
You'll have to wait for next version of EEO though.
