### ISSUE TITLE
Planet product error

### ISSUE THREAD

**Issue by jteulade** [sertit/eoreader#169]
With this product: `s3://sertit-rms2/archives/rms/2021/EMSN100_Wildfire_LaRioja_STD/DATA/a_Satellite Imagery/RAW`
I get this error:
```
Traceback (most recent call last):
  File "E:\JTeulade\repositories\stac\scripts\test.py", line 26, in <module>
    func()
  File "E:\JTeulade\repositories\stac\libs\sertit-utils\sertit\s3.py", line 118, in s3_env_wrapper
    return function(*_args, **_kwargs)
  File "E:\JTeulade\repositories\stac\scripts\test.py", line 18, in func
    prod: Product = Reader().open(tata, remove_tmp=True, method=CheckMethod.MTD)
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 528, in open
    prod = self._open_path(
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 690, in _open_path
    prod = create_product(
  File "e:\jteulade\repositories\eoreader\eoreader\reader.py", line 957, in create_product
    prod = class_(
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\planet_product.py", line 147, in __init__
    super().__init__(product_path, archive_path, output_path, remove_tmp, **kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\optical_product.py", line 116, in __init__
    super().__init__(product_path, archive_path, output_path, remove_tmp, **kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\product.py", line 268, in __init__
    self._post_init(**kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\pla_product.py", line 215, in _post_init
    super()._post_init(**kwargs)
  File "e:\jteulade\repositories\eoreader\eoreader\products\optical\planet_product.py", line 207, in _post_init
    path.get_filename(self._get_stack_path(as_list=False)).upper().split("_")
  File "E:\JTeulade\repositories\stac\libs\sertit-utils\sertit\path.py", line 322, in get_filename
    file_path = AnyPath(file_path)
  File "C:\Users\jteulade\AppData\Local\anaconda3\envs\arcgispro-eo\lib\site-packages\cloudpathlib\anypath.py", line 34, in __new__
    raise AnyPathTypeError(
cloudpathlib.exceptions.AnyPathTypeError: Invalid input for both CloudPath and Path. CloudPath exception: InvalidPrefixError("Path [] does not begin with a known prefix ['az://', 's3://', 'gs://'].") Path exception: TypeError('expected str, bytes or os.PathLike object, not list')

```

**Comment by remi-braun** [comment]
It seems `RAW` is not a Planet Product, am I right?
Did you checked it? You have Planet products inside `RAW/POST` and `RAW/PRE` though

**Comment by remi-braun** [comment]
A better handling of this case has been implemented 😄
